Fully-qualify std::swap for pointer/size_t. (#27)
The ustream clang dev branch found this unqualified swap:
```
ducc/src/ducc0/infra/aligned_array.h:135:7: error: use of undeclared identifier 'swap'
  135 |       swap(sz, other.sz);
```
It seems the function isn't ever actually used, which is why it wasn't
previously uncovered.  The latest clang, however, is enforcing more strict
checks on template code, leading to build failures.